name: Test Hyprland Installer

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest # usaremos docker para simular o Arch

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run Arch container
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace archlinux:latest bash -c "
          pacman -Sy --noconfirm sudo git base-devel
          useradd -m tester
          echo 'tester ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
          echo -e '\n#[multilib]\n#Include = /etc/pacman.d/mirrorlist' >> /etc/pacman.conf
          cp -r /workspace /home/tester/
          chown -R tester:tester /home/tester/workspace
          su - tester -c 'cd /home/tester/workspace && chmod +x setup.sh && ./setup.sh' "